name: Android CI

on:
  push:
    tags:
      - "v*"     # 推送 tag（例如 v1.0.0）时触发
  workflow_dispatch:   # 允许手动触发

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. 拉取代码
      - name: Checkout
        uses: actions/checkout@v4

      # 2. 设置 JDK 环境（XPlan 用 Java 17）
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      # 3. 赋予 Gradle 执行权限
      - name: Make gradlew executable
        run: chmod +x ./gradlew

      # 4. 构建 Debug APK（如果要 Release，就改 assembleRelease）
      - name: Build APK
        run: ./gradlew assembleDebug

      # 5. 上传 APK 作为 GitHub Actions 的构建产物（方便下载）
      - name: Upload APK as artifact
        uses: actions/upload-artifact@v4
        with:
          name: XPlan-Debug-APK
          path: app/build/outputs/apk/debug/app-debug.apk

      # 6. （可选）发布到 GitHub Release（只有推送 tag 时执行）
      - name: Upload to GitHub Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: app/build/outputs/apk/debug/app-debug.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
