name: Build Android APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:   # ✅ 手动触发支持

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      - name: Fix JVM args for Java 17
        run: |
          # 删除所有 gradle.properties 中的 MaxPermSize 参数
          grep -rl --include=gradle.properties "MaxPermSize" . | xargs -r sed -i 's/-XX:MaxPermSize=512m//g'
          # 写入新的 JVM 参数
          echo "org.gradle.jvmargs=-Xmx2g -Dfile.encoding=UTF-8" > gradle.properties
          # 禁用 Daemon 避免继承错误参数
          echo "org.gradle.daemon=false" >> gradle.properties

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew assembleRelease --stacktrace

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: release-apk
          path: app/build/outputs/apk/release/*.apk